### ISSUE TITLE
Roadmap for v0.1.0

### ISSUE THREAD

**Issue by leozdgao** [leozdgao/node-skia-canvas#1]
Implementing HTML Canvas API for v0.1.0, including:

#### properties
- [x] width
- [x] height

#### methods
- [x] getContext() `'2d' only for now`
- ~toDataUrl()~
- ~toBlob()~
- [x] ✨ toBuffer()

#### properties
- [x] fillStyle
- [x] font
- [x] globalAlpha
- ~~globalCompositeOperation~~ `move to 0.2.0`
- [x] imageSmoothingEnabled
- [x] lineCap
- [x] lineDashOffset
- [x] lineJoin
- [x] lineWidth
- [x] miterLimit
- [x] shadowBlur
- [x] shadowColor
- [x] shadowOffsetX
- [x] shadowOffsetY
- [x] strokeStyle
- [x] textAlign
- [x] textBaseline

#### methods
- [x] arc()
- [x] arcTo()
- [x] beginPath()
- [x] bezierCurveTo()
- [x] clearRect()
- [x] clip()
- [x] closePath()
- ~createConicGradient()~
- [x] createImageData()
- [x] createLinearGradient()
- [x] createPattern()
- [x] createRadialGradient()
- ~drawFocusIfNeeded()~
- [x] drawImage()
- [x] ellipse()
- [x] fill() `not support Path2D for first version`
- [x] fillRect()
- [x] fillText()
- ~getContextAttributes()~
- [x] getImageData()
- [x] getLineDash()
- [x] getTransform()
- ~isPointInPath()~
- ~isPointInStroke()~
- [x] lineTo()
- [x] measureText()
- [x] moveTo()
- [x] putImageData()
- [x] quadraticCurveTo()
- [x] rect()
- [x] restore()
- [x] rotate()
- [x] save()
- [x] scale()
- [x] setLineDash()
- [x] setTransform()
- [x] stroke() `not support Path2D for first version`
- [x] strokeRect()
- [x] strokeText()
- [x] transform()
- [x] translate()

#### Image
- [x] width, height
- [x] src getter & setter

#### registerFont
- [x] registerFont

### Node Package
- [x] test case
- [x] prebuilt
- [x] README
